# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 146cb46db24228559cb936b7d89ff62f6ed36e0d9f65117513c818f4a2aa7914090c846da68240779e7550d70c2e79dd9bd106885180e23e428c0e136acbfedf

test:
  secret_key_base: b49f4381c045260c72d464396e9a3652cdd00ab87a9c1798e899cf5386fab55a9373ab3df5a7bfb011012d8cc7f668aaeb7dc2392d6f64ba9b6f4be99f661b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
